### ISSUE TITLE
Pas d'import de l'ISNI alors qu'il est dans la zone 024

### ISSUE THREAD

**Issue by PierreGravier** [abes-esr/idref-xslt#10]
@Francois-Mistral
Concerne : https://github.com/abes-esr/idref-xslt/blob/master/marc21viaftoidref.xsl

Des notices comprennent souvent l'ISNI dans la zone 024 :
https://viaf.org/processed/BNE%7CXX112707

Or, après l'import, on ne le retrouve pas en zone 010 :
279145209

**Comment by Francois-Mistral** [comment]
Bonjour,
encore merci.
Je viens d'ajouter dans l'XSL de quoi récupérer l'ISNI (en 010) s'il est présent (en 024).
A+

**Comment by PierreGravier** [comment]
Merci François !
