### ISSUE TITLE
Pas d'import du n° ISNI quand on importe une notice... de l'ISNI depuis Viaf

### ISSUE THREAD

**Issue by PierreGravier** [abes-esr/idref-xslt#12]
@Francois-Mistral
Concerne : https://github.com/abes-esr/idref-xslt/blob/master/marc21viaftoidref.xsl

On ne retrouve pas le numéro ISNI en zone 010 dans l'autorité Sudoc alors qu'on a importé depuis Viaf une notice ISNI qui le mentionne en zone 001.

Par exemple, je viens d'importer : https://viaf.org/processed/ISNI%7C0000000087512498
Et cela donne : https://www.idref.fr/280153260

Je la laisse temporairement en l'état.

**Comment by Francois-Mistral** [comment]
L'id ISNI est maintenant introduit dans l'XSL.
Ticket traité.
