### ISSUE TITLE
Import de la BN Pologne (https://viaf.org/viaf/partnerpages/PLWABN.html)

### ISSUE THREAD

**Issue by PierreGravier** [abes-esr/idref-xslt#6]
@Francois-Mistral 

Concerne : https://github.com/abes-esr/idref-xslt/blob/master/marc21viaftoidref.xsl

Lors de l'import de notices de la BN Pologne (pas Nukat) depuis Viaf, l'import échoue (à 2 occasions) sur la zone 103 (KO, Message : Veuillez compléter la zone 103). Par exemple : https://viaf.org/processed/PLWABN%7C9812404746005606

**Comment by Francois-Mistral** [comment]
Une chose que je ne comprends pas  : 
la notice a été dérivée : 278590284.
Le blocage s'est-il levé tout seul ?

**Comment by PierreGravier** [comment]
La notice a été dérivée depuis Nukat (aussi polonais) pour contourner le fait que la dérivation depuis la BN Pologne n'était pas possible. Le blocage n'est donc pas levé.

**Comment by Francois-Mistral** [comment]
Ok j'ai compris.
Et j'ai corrigé : la notice BN Pologne a été dérivée ici : 278729835
