### ISSUE TITLE
Plusieurs zones 110 / 210 dans des notices, notamment ISNI

### ISSUE THREAD

**Issue by PierreGravier** [abes-esr/idref-xslt#7]
@Francois-Mistral
Concerne : https://github.com/abes-esr/idref-xslt/blob/master/marc21viaftoidref.xsl

Pour des notices à importer depuis Viaf qui ont plusieurs zones de nom principal (zones 110 > future zone 210).

Un exemple d'échec répété d'import de métadonnées ISNI depuis Viaf : https://viaf.org/processed/ISNI%7C0000000102054537
Donne comme message : La zone 210 n'est pas répétable si les $6 et $7 sont absents

**Comment by Francois-Mistral** [comment]
Bonjour @PierreGravier 
le pb avec ISNI est qu'il fait une liste de formes, sans choisir une variante privilégiée comme l'attend le format.
ISNI est donc une mauvaise source au sens où on ne peut dériver puisque le travail intellectuel n'a pas été mené.
Dans ce cas, il faut créer une notice par formulaire avec les informations utiles de la notice ISNI.
Bien à toi.

**Comment by PierreGravier** [comment]
Merci François, on l'intègre à la procédure (choisir un autre référentiel ou créer manuellement en ajoutant ultérieurement l'ISNI).
