### ISSUE TITLE
Sous-zone $a manquante en 810

### ISSUE THREAD

**Issue by PierreGravier** [abes-esr/idref-xslt#8]
@Francois-Mistral
Concerne : https://github.com/abes-esr/idref-xslt/blob/master/marc21viaftoidref.xsl

Un cas rare d'échec d'import en raison de la structuration de la future zone 810 :
https://viaf.org/processed/PLWABN%7C9812646856205606

Message d'erreur : Message : La sous-zone $a est obligatoire en 810

**Comment by Francois-Mistral** [comment]
Bonjour,
je viens d'ajouter dans l'xsl le traitement particulier du cas où la 810 ne contient pas de $a mais un $u. Il est alors transformé en $a.

La dérivation a donc fonctionné : PPN 279136080
A+

**Comment by PierreGravier** [comment]
Grand merci ! 👍
