### ISSUE TITLE
Import d'une notice de collectivité en Unimarc analysée comme une notice Tp

### ISSUE THREAD

**Issue by PierreGravier** [abes-esr/idref-xslt#9]
@Francois-Mistral
Concerne : https://github.com/abes-esr/idref-xslt/blob/master/marc21viaftoidref.xsl

Un nouveau cas que je ne comprends pas. IdRef à l'import annonce une zone 210 incompatible avec une notice Tp. En soi, formulé comme ça, c'est logique, sauf que la notice que je cherche à importer est bien référencée "Collectivité" par Viaf. C'est d'autant plus surprenant que, pour une fois, la notice semble en Unimarc :
https://viaf.org/processed/LIH%7CLNB:1_e_D;=BA

Message d'erreur : La zone 210 n'est pas compatible avec le type de document Tp

**Comment by Francois-Mistral** [comment]
La réponse est simple : ici la notice lituanienne de base est en Unimarc. 
Or l'XSL qui transforme en unimarc n'a pas été modifié pour permettre la dérivation de Collectivités : c'est plus compliqué côté code et moins pertinent côté sources qui sont moins nombreuses et moins pertinentes dans l'absolu.
Je préconise un contournement : dériver une notice polonaise (en marc21) et ajouter des données issues de la BN lituanienne.

**Comment by Francois-Mistral** [comment]
Ceci dit : as-tu vu cette notice : 251409082 ?

**Comment by PierreGravier** [comment]
C'est noté, on oublie les notices en Unimarc.

Pour 251409082, en regardant, c'est un compositeur de musique légère (dixit la BnF, et en effet : _Ma petite gigolette_, _Le jupon de Madelon_...). Sans lui manquer de respect, l'éditeur du même nom actif entre 1889-1925 publie plutôt des revues de philologie, d'antiquités égyptiennes... Je doute que ce soit le bon, sans certitude !
